/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#1976d2",
        "error-container": "#ffdad6",
        "status-partial": "#ED6C02",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "transaction-add": "#2E7D32",
        "surface-container": "#efeded",
        "primary-fixed-dim": "#a5c8ff",
        "secondary": "#9c4400",
        "on-background": "#1b1c1c",
        "surface-tint": "#005faf",
        "primary": "#005dac",
        "on-secondary-container": "#5b2500",
        "status-repair": "#FBC02D",
        "on-primary-container": "#fffdff",
        "inverse-surface": "#303031",
        "on-surface-variant": "#414752",
        "tertiary": "#9822ad",
        "on-secondary-fixed": "#331200",
        "surface-dim": "#dbdad9",
        "tertiary-container": "#b542c8",
        "outline": "#717783",
        "on-secondary-fixed-variant": "#773300",
        "surface-variant": "#e3e2e2",
        "transaction-sell": "#D32F2F",
        "secondary-fixed-dim": "#ffb68e",
        "on-error-container": "#93000a",
        "primary-fixed": "#d4e3ff",
        "on-tertiary-container": "#fffdff",
        "surface-container-low": "#f5f3f3",
        "surface": "#fbf9f9",
        "tertiary-fixed-dim": "#f9abff",
        "secondary-fixed": "#ffdbca",
        "surface-container-high": "#e9e8e7",
        "on-tertiary-fixed": "#35003f",
        "surface-bright": "#fbf9f9",
        "error": "#ba1a1a",
        "status-hold": "#9C27B0",
        "tertiary-fixed": "#ffd6fe",
        "status-active": "#1976D2",
        "transaction-adjustment": "#9C27B0",
        "background": "#fbf9f9",
        "status-archived": "#757575",
        "on-tertiary-fixed-variant": "#7b008f",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "on-primary-fixed": "#001c3a",
        "surface-container-highest": "#e3e2e2",
        "status-success": "#2E7D32",
        "surface-container-lowest": "#ffffff",
        "status-sold-out": "#D32F2F",
        "on-surface": "#1b1c1c",
        "outline-variant": "#c1c6d4",
        "on-primary-fixed-variant": "#004786",
        "inverse-primary": "#a5c8ff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fc7716",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xxl: "32px",
        xl: "24px",
        huge: "48px",
        gutter: "16px",
        lg: "16px",
        md: "12px",
        xs: "4px",
        base: "4px",
        "margin-page": "24px",
        sm: "8px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "kpi-numeric": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "kpi-numeric": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
