export enum VERSION_CHECKPOINT_EVENTS {
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_REMOVED = 'ITEM_REMOVED',
  ITEM_BULK_EDITED = 'ITEM_BULK_EDITED',
  PARTY_CHANGED = 'PARTY_CHANGED',
  STOCK_CHANGED = 'STOCK_CHANGED',
  TRANSACTION_TYPE_CHANGED = 'TRANSACTION_TYPE_CHANGED',
  CERTIFICATION_ADDED = 'CERTIFICATION_ADDED',
  REPAIR_ADDED = 'REPAIR_ADDED',
  REPAIR_COMPLETED = 'REPAIR_COMPLETED',
  MULTIPLE_4C_CHANGED = 'MULTIPLE_4C_CHANGED',
  TOTAL_VALUE_CHANGED_SIGNIFICANTLY = 'TOTAL_VALUE_CHANGED_SIGNIFICANTLY',
  TRANSACTION_AUTHORIZED = 'TRANSACTION_AUTHORIZED'
}

export function shouldCreateCheckpoint(event: VERSION_CHECKPOINT_EVENTS): boolean {
  // All defined events in the enum currently trigger an immediate checkpoint.
  return Object.values(VERSION_CHECKPOINT_EVENTS).includes(event);
}
