export enum PartyType {
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
  WORKSHOP = 'WORKSHOP',
  CERTIFICATION_LAB = 'CERTIFICATION_LAB',
  OTHER = 'OTHER'
}

export enum LedgerType {
  INVENTORY = 'INVENTORY',
  FINANCIAL = 'FINANCIAL'
}

export enum TransactionType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  RETURN = 'RETURN',
  REPAIR = 'REPAIR',
  CERTIFICATION = 'CERTIFICATION',
  TRANSFER = 'TRANSFER',
  ADJUSTMENT = 'ADJUSTMENT',
  ADD_IN = 'ADD_IN',
  WRITE_OFF = 'WRITE_OFF',
  TRANSFORMATION = 'TRANSFORMATION'
}

export enum TransactionItemAction {
  ADDED = 'ADDED',
  REMOVED = 'REMOVED',
  UPDATED = 'UPDATED'
}

export enum ItemEventType {
  PURCHASED = 'PURCHASED',
  SOLD = 'SOLD',
  RETURNED = 'RETURNED',
  REPAIRED = 'REPAIRED',
  CERTIFIED = 'CERTIFIED',
  TRANSFERRED = 'TRANSFERRED',
  ADJUSTED = 'ADJUSTED',
  WRITTEN_OFF = 'WRITTEN_OFF',
  TRANSFORMED = 'TRANSFORMED'
}

export enum CertificationStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  ISSUED = 'ISSUED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  REPLACED = 'REPLACED',
  CANCELLED = 'CANCELLED'
}

export enum RepairStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum RepairType {
  REPOLISH = 'REPOLISH',
  SETTING_REPAIR = 'SETTING_REPAIR',
  CHIP_REPAIR = 'CHIP_REPAIR',
  SYMMETRY_CORRECTION = 'SYMMETRY_CORRECTION',
  SURFACE_REPAIR = 'SURFACE_REPAIR',
  OTHER = 'OTHER'
}

export enum TransformationType {
  CUT = 'CUT',
  RECUT = 'RECUT',
  POLISH = 'POLISH',
  REPOLISH = 'REPOLISH',
  REWORK = 'REWORK',
  SPLIT = 'SPLIT',
  MERGE = 'MERGE',
  RECLASSIFICATION = 'RECLASSIFICATION',
  OTHER = 'OTHER'
}

export enum MovementType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  RETURN = 'RETURN',
  TRANSFER = 'TRANSFER',
  REPAIR_OUT = 'REPAIR_OUT',
  REPAIR_IN = 'REPAIR_IN',
  WRITE_OFF = 'WRITE_OFF',
  ADJUSTMENT = 'ADJUSTMENT',
  TRANSFORMATION = 'TRANSFORMATION'
}

export enum ItemStatus {
  AVAILABLE = 'AVAILABLE',
  SOLD = 'SOLD',
  IN_REPAIR = 'IN_REPAIR',
  WRITTEN_OFF = 'WRITTEN_OFF',
  IN_TRANSIT = 'IN_TRANSIT',
  RESERVED = 'RESERVED'
}

export enum CertificateState {
  NONE = 'NONE',
  PENDING = 'PENDING',
  RECEIVED = 'RECEIVED'
}

export enum FinancialEntryType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  REFUND = 'REFUND',
  REPAIR_EXPENSE = 'REPAIR_EXPENSE',
  CERTIFICATION_EXPENSE = 'CERTIFICATION_EXPENSE',
  ADJUSTMENT = 'ADJUSTMENT',
  WRITE_OFF = 'WRITE_OFF',
  OTHER = 'OTHER'
}

export enum ValuationType {
  PURCHASE_COST = 'PURCHASE_COST',
  MARKET_REVALUATION = 'MARKET_REVALUATION',
  REPAIR_REVALUATION = 'REPAIR_REVALUATION',
  CERTIFICATION_REVALUATION = 'CERTIFICATION_REVALUATION',
  ADJUSTMENT = 'ADJUSTMENT',
  SALE = 'SALE',
  OTHER = 'OTHER'
}
